- name: "VAULT_CLIENT | Assert inputs | ca/create_intermediate_ca.yml"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_pki_name is defined) and (_pki_name|length > 0)
      - (_common_name is defined) and (_common_name|length > 0)
      - (_ttl is defined) and (_ttl|length > 0)
      - (_root_pki_name is defined) and (_root_pki_name|length > 0)
      # Optional
      # - _issuer_name
      # - _country
      # - _organization
      # - _alt_names
    fail_msg: "Variable must be defined and not empty"

- name: "VAULT_CLIENT | Set pki_name_full"
  ansible.builtin.set_fact:
    pki_name_full: "pki_int_{{ _pki_name }}"

- name: "VAULT_CLIENT | PKI Intermediate CA | Check if pki secrets engine already exists"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/sys/mounts/{{ pki_name_full }}"
    validate_certs: false
    method: GET
    headers:
      Authorization: "Bearer {{ _vault_token }}"
    status_code: 200, 400
    body_format: json
    body:
      type: "pki"
  register: pki

- name: "VAULT_CLIENT | PKI Intermediate CA | Create intermediate CA"
  when: pki.status != 200
  block:
    - name: "VAULT_CLIENT | PKI Intermediate CA | Enable the pki secrets engine at {{ pki_name_full }} path."
      ansible.builtin.uri:
        url: "{{ vault.url.internal }}/v1/sys/mounts/{{ pki_name_full }}"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ _vault_token }}"
        status_code: 200, 204
        body_format: json
        body:
          type: "pki"

    - name: "VAULT_CLIENT | PKI Intermediate CA | Tune the {{ pki_name_full }} secrets engine to issue certificates with a maximum time-to-live (TTL) of {{ _ttl }}."
      ansible.builtin.uri:
        url: "{{ vault.url.internal }}/v1/sys/mounts/{{ pki_name_full }}/tune"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ _vault_token }}"
        status_code: 200, 204
        body_format: json
        body:
          max_lease_ttl: "{{ _ttl }}"

    - name: "VAULT_CLIENT | PKI Intermediate CA | Generate an intermediate certificate using the /{{ pki_name_full }}/intermediate/generate/internal endpoint"
      ansible.builtin.uri:
        url: "{{ vault.url.internal }}/v1/{{ pki_name_full }}/intermediate/generate/internal"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ _vault_token }}"
        status_code: 200, 204
        body_format: json
        body:
          common_name: "{{ _common_name }}"
          alt_names: "{{ _alt_names | default('') }}"
          issuer_name: "{{ _issuer_name | default('') }}"
          organization: "{{ _organization | default('') }}"
          country: "{{ _country | default('') }}"
          use_common_name_for_san: true
          ttl: "{{ _ttl }}"
      register: intermediate_ca

    - name: "VAULT_CLIENT | PKI Intermediate CA | Assert intermediate ca"
      ansible.builtin.assert:
        that:
          - (intermediate_ca is defined) and (intermediate_ca|length > 0) and (intermediate_ca.json.data.csr is defined) and (intermediate_ca.json.data.csr |length > 0)
        fail_msg: "Intermediate CA must be created"


    - name: "VAULT_CLIENT | PKI Intermediate CA | Sign the intermediate certificate with the root CA private key"
      ansible.builtin.uri:
        url: "{{ vault.url.internal }}/v1/{{ _root_pki_name }}/root/sign-intermediate"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ _vault_token }}"
        status_code: 200, 204
        body_format: json
        body:
          csr: "{{ intermediate_ca.json.data.csr }}"
          format: "pem_bundle"
          ttl: "{{ _ttl }}"
      register: intermediate_cert

    - name: "VAULT_CLIENT | PKI Intermediate CA | Assert intermediate_cert"
      ansible.builtin.assert:
        that:
          - (intermediate_cert is defined) and (intermediate_cert|length > 0) and (intermediate_cert.json.data.certificate is defined) and (intermediate_cert.json.data.certificate |length > 0)
        fail_msg: "intermediate_cert must be created"

    - name: "VAULT_CLIENT | PKI Intermediate CA | Submit the signed certificate."
      ansible.builtin.uri:
        url: "{{ vault.url.internal }}/v1/{{ pki_name_full }}/intermediate/set-signed"
        validate_certs: false
        method: POST
        headers:
          Authorization: "Bearer {{ _vault_token }}"
        status_code: 200, 204
        body_format: json
        body:
          certificate: "{{ intermediate_cert.json.data.certificate }}"
          format: "pem_bundle"
          ttl: "{{ _ttl }}"
