---
- name: Apply create_kv_secret_engine role tasks
  ansible.builtin.include_role:
    name: "{{ role_path }}"
    tasks_from: create_kv_secret_engine
  vars:
    _kv_secret_engine_name: "{{ kv_secret_engine.name }}"

- name: "Assert KV Secret Engine '{{ kv_secret_engine.name }}' exists"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/sys/mounts/{{ kv_secret_engine.name }}/"
    validate_certs: false
    method: GET
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    status_code: 200
  register: output_get_kv_secret_engine
  changed_when: false

- name: "Assert KV Secret Engine '{{ kv_secret_engine.name }}' type is correct"
  ansible.builtin.assert:
    that:
      - output_get_kv_secret_engine.json.data.type == "kv"
    fail_msg: "KV Secret Engine '{{ kv_secret_engine.name }}' type does not match expected type 'kv'"
