### Inputs
- name: "VAULT_CLIENT | Assert inputs | create_kv_secret_engine.yml"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_kv_secret_engine_name is defined) and (_kv_secret_engine_name|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "VAULT_CLIENT | Create KV secret engine '{{ _kv_secret_engine_name }}'"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/sys/mounts/{{ _kv_secret_engine_name }}"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    body_format: json
    body:
      type: kv
      description: "{{ kv_secret_engine_description| default('') }}"
      options:
        version: "{{ kv_secret_engine_version | default('2') }}"
    status_code: 204, 400
  register: output_create_kv_secret_engine
  changed_when: output_create_kv_secret_engine.status == 204
