### Inputs
- name: "VAULT_CLIENT | Assert inputs | create_approle.yml"
  when: (_approle_policies|length > 0)
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)           # URL of Vault
      - (_vault_token is defined) and (_vault_token|length > 0)     # Token to authenticate with Vault
      - (_vault_token is defined) and (_vault_token|length > 0)     # Token to authenticate with Consul
      - (_approle_name is defined) and (_approle_name|length > 0)   # Name of the app rol to be created
    # Optional
    # _store_approle_config_in_consul: false                        # Boolean (default=true); If true, the app role config will be stored in Consul

- name: "VAULT_CLIENT | Assert conditional inputs | create_approle.yml"
  when: (_store_approle_config_in_consul|default(true))
  ansible.builtin.assert:
    that:
      - (_consul_token is defined) and (_consul_token|length > 0)    # Token to authenticate with Consul


- name: "VAULT_CLIENT | Create app role '{{ _approle_name }}'"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/auth/approle/role/{{ _approle_name }}"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    status_code: 200, 204
  no_log: false

- name: "VAULT_CLIENT | Set app role id to app role name '{{ _approle_name }}'"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/auth/approle/role/{{ _approle_name }}/role-id"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    body_format: json
    body:
      role_id: "{{ _approle_name }}"
    status_code: 200, 204
  no_log: false

- name: "VAULT_CLIENT | Create secret id for app role with id '{{ _approle_name }}'"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/auth/approle/role/{{ _approle_name }}/secret-id"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    status_code: 200, 204
  register: request_secret_id
  no_log: false

- name: "VAULT_CLIENT | Set fact for role id and secret id of app role '{{ _approle_name }}'"
  ansible.builtin.set_fact:
    role_id: "{{ _approle_name }}"
    secret_id: "{{ request_secret_id.json.data.secret_id }}"

- name: "VAULT_CLIENT | Store config for app role '{{ _approle_name }}' in Consul"
  when: (_store_approle_config_in_consul|default(true))
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: create_or_add_config
  vars:
    _app_name: "{{ _approle_name }}"
    _config:
      vault:
        app-role:
          role-id: '{{ role_id}}'
          secret-id: '{{ secret_id}}'

### Outputs
- name: "VAULT_CLIENT | Set facts for outputs"
  ansible.builtin.set_fact:
    vault_approle_role_id: "{{ role_id }}"        # Role id of the created app role
    vault_approle_secret_id: "{{ secret_id }}"    # Secret id of the created app role
