### Inputs
- name: "VAULT_CLIENT | Assert inputs | write_kv_secret.yml"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_kv_secret_engine_name is defined) and (_kv_secret_engine_name|length > 0)
      - (_kv_secret_engine_path is defined) and (_kv_secret_engine_path|length > 0)
      - (_kv_secret_engine_data is defined) and (_kv_secret_engine_data|length > 0)
    fail_msg: "Variable must be defined and not empty"

### Optional Inputs
# - _kv_custom_metadata: Optional custom metadata for the KV secret engine. Default is empty.

- name: "VAULT_CLIENT | Write KV secret to '{{ _kv_secret_engine_name }}'"
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/{{ _kv_secret_engine_name }}/data/{{_kv_secret_engine_path}}"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    body_format: json
    body:
      data: "{{ _kv_secret_engine_data }}"
    status_code: 200
  register: output_write_kv_secret
  changed_when: false

- name: "VAULT_CLIENT | Write Meta Data of '{{ _kv_secret_engine_name }}' KV secret engine to '{{ _kv_secret_engine_path }}'"
  when: (_kv_custom_metadata is defined) and (_kv_custom_metadata|length > 0)
  ansible.builtin.uri:
    url: "{{ vault.url.internal }}/v1/{{ _kv_secret_engine_name }}/metadata/{{_kv_secret_engine_path}}"
    validate_certs: false
    method: POST
    headers:
      X-Vault-Token: "{{ _vault_token }}"
    body_format: json
    body:
      custom_metadata: "{{ _kv_custom_metadata | default({}) }}"
    status_code: 200, 204
  register: output_write_kv_secret
  changed_when: false
