---
### Inputs
- name: "Assert inputs of 'vault/client | write_kv_resource_credentials.yml'"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_resource_remote_access_service_id is defined) and (_resource_remote_access_service_id|length > 0)
      - (_resource_username is defined) and (_resource_username|length > 0)
      - (_resource_password is defined) and (_resource_password|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Assure KV secret engine is created and write credentials of '{{ _resource_remote_access_service_id }}' to '{{ _kv_secret_engine_name }}'"
  ansible.builtin.include_tasks: "{{ role_path }}/{{ item }}.yml"
  vars:
    _kv_secret_engine_name: "resources"
    _kv_secret_engine_description: "resources secret engine"
    _kv_secret_engine_version: "{{ _kv_secret_engine_version | default('2') }}"
    _kv_secret_engine_path: "{{ _resource_remote_access_service_id }}/CredentialUsernamePassword"
    _kv_secret_engine_data:
      username: "{{ _resource_username }}"
      password: "{{ _resource_password }}"
  loop:
    - "create_kv_secret_engine"
    - "write_kv_secret"
